<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/raWWar/raWWar.csproj" />
    <Content Include="../../data/*.json" Link="data/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../runtime-manifest.json" Link="runtime-manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../experience-manifest.json" Link="experience-manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
